title: Sammy The Hobbyist
description: A website with a blog
footer_text: Copyright 2021 Sammy
header_feature_image: ../uploads/pages.jpg
header_text: Storytelling and Fibre Crafts
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
